#!/bin/bash
#
# Installs the helper app for the "Menubar for Symfony" GNOME Shell extension.
#
# Nothing is compiled and nothing is downloaded: the helper is plain JavaScript
# run by /usr/bin/gjs, which every system running GNOME Shell already has. No
# root privileges are needed — everything lands under your home directory.
#
# Usage: daemon/install.sh   (or: npm run install-daemon)

set -euo pipefail

BUNDLE_NAME="symfony-menubar-daemon.js"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="$ROOT/dist/daemon/$BUNDLE_NAME"

DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/symfony-menubar-daemon"
BIN_DIR="$HOME/.local/bin"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/symfony-menubar"
WRAPPER="$BIN_DIR/symfony-menubar-daemon"

if [ ! -f "$SOURCE" ]; then
    echo "Error: $SOURCE not found. Run 'npm run build' first." >&2
    exit 1
fi

if ! command -v gjs >/dev/null; then
    echo "Error: gjs was not found on PATH." >&2
    echo "It ships with GNOME Shell; install the 'gjs' package if it is missing." >&2
    exit 1
fi

GJS="$(command -v gjs)"

echo "Installing the helper app"

mkdir -p "$DATA_DIR" "$BIN_DIR" "$CONFIG_DIR"
install -m 644 "$SOURCE" "$DATA_DIR/$BUNDLE_NAME"
echo "  helper      $DATA_DIR/$BUNDLE_NAME"

cat > "$WRAPPER" <<EOF
#!/bin/sh
# Generated by daemon/install.sh
exec "$GJS" -m "$DATA_DIR/$BUNDLE_NAME" "\$@"
EOF
chmod 755 "$WRAPPER"
echo "  launcher    $WRAPPER"

# Registers the helper for D-Bus activation, so the extension never starts a
# process itself: the session bus starts it on the first method call.
"$WRAPPER" --install-service

# The old location was inside the extension directory, which GNOME replaces on
# every extension update.
LEGACY_ACTIONS="$HOME/.local/share/gnome-shell/extensions/menubar-for-symfony@tito10047.github.com/actions.json"
if [ -f "$LEGACY_ACTIONS" ] && [ ! -f "$CONFIG_DIR/actions.json" ]; then
    cp "$LEGACY_ACTIONS" "$CONFIG_DIR/actions.json"
    echo "  actions     migrated to $CONFIG_DIR/actions.json"
fi

echo
echo "Done. Custom actions belong in $CONFIG_DIR/actions.json"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "Note: $BIN_DIR is not on your PATH. D-Bus activation works regardless;"
       echo "      add it if you want to run 'symfony-menubar-daemon' by hand." ;;
esac

if gdbus call --session --dest org.freedesktop.DBus --object-path /org/freedesktop/DBus \
        --method org.freedesktop.DBus.GetNameOwner com.github.tito10047.SymfonyMenubar >/dev/null 2>&1; then
    echo "Note: an older helper is still running. Run 'symfony-menubar-daemon --replace'"
    echo "      or toggle the extension off and on to pick up this version."
fi
